# Generated by Django 5.0.2 on 2024-03-19 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ITMetaField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='IT_Live_Chat_Admin_Sound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_live_chat_notification_sound', models.FileField(blank=True, null=True, upload_to='it/sound/admin_live_chat_notification_sound/')),
                ('admin_live_call_ringtone', models.FileField(blank=True, null=True, upload_to='it/sound/admin_live_call_ringtone/')),
                ('user_cannot_call_admin_sound', models.FileField(blank=True, null=True, upload_to='it/sound/user_cannot_call_admin_sound/')),
            ],
        ),
        migrations.CreateModel(
            name='IT_User_Order_Sound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_chat_notification_tone', models.FileField(blank=True, null=True, upload_to='it/sound/order_chat_notification_tone/')),
                ('order_call_ringtone', models.FileField(blank=True, null=True, upload_to='it/sound/order_call_ringtone/')),
            ],
        ),
        migrations.CreateModel(
            name='IT_User_Sound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_entry_sound', models.FileField(blank=True, null=True, upload_to='it/sound/entry_sound/')),
                ('live_chat_talk_sound', models.FileField(blank=True, null=True, upload_to='it/sound/live_chat_talk_sound/')),
                ('live_chat_turned_off_sound', models.FileField(blank=True, null=True, upload_to='it/sound/live_chat_turned_off_sound/')),
                ('user_live_chat_notification_sound', models.FileField(blank=True, null=True, upload_to='it/sound/user_live_chat_notification_sound/')),
                ('user_live_call_ringtone', models.FileField(blank=True, null=True, upload_to='it/sound/user_live_call_ringtone/')),
            ],
        ),
        migrations.CreateModel(
            name='IT_BlogCard',
            fields=[
                ('itmetafield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='it_dashboard.itmetafield')),
                ('image', models.ImageField(blank=True, null=True, upload_to='it/image/blog-card/')),
                ('title', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            bases=('it_dashboard.itmetafield',),
        ),
        migrations.CreateModel(
            name='IT_CardTemplate',
            fields=[
                ('itmetafield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='it_dashboard.itmetafield')),
                ('image', models.ImageField(blank=True, null=True, upload_to='it/image/template-card/')),
                ('title', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            bases=('it_dashboard.itmetafield',),
        ),
        migrations.CreateModel(
            name='IT_Company_Member',
            fields=[
                ('itmetafield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='it_dashboard.itmetafield')),
                ('image', models.ImageField(blank=True, null=True, upload_to='it/image/company-member/')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=150)),
                ('phone_number', models.CharField(max_length=14)),
                ('address', models.CharField(max_length=500)),
            ],
            bases=('it_dashboard.itmetafield',),
        ),
        migrations.CreateModel(
            name='IT_Contact_Us',
            fields=[
                ('itmetafield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='it_dashboard.itmetafield')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=150)),
                ('phone_number', models.CharField(max_length=15)),
                ('subject', models.CharField(max_length=600)),
                ('message', models.TextField()),
            ],
            bases=('it_dashboard.itmetafield',),
        ),
        migrations.CreateModel(
            name='IT_Footer_Section_Topics',
            fields=[
                ('itmetafield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='it_dashboard.itmetafield')),
                ('title', models.CharField(max_length=50)),
                ('topic_url', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            bases=('it_dashboard.itmetafield',),
        ),
        migrations.CreateModel(
            name='IT_FourCardSection',
            fields=[
                ('itmetafield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='it_dashboard.itmetafield')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='it/image/four-card-icons/')),
                ('title', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            bases=('it_dashboard.itmetafield',),
        ),
        migrations.CreateModel(
            name='IT_Global_Location',
            fields=[
                ('itmetafield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='it_dashboard.itmetafield')),
                ('flag_logo', models.ImageField(blank=True, null=True, upload_to='it/image/global-location-flag/')),
                ('country_name', models.CharField(max_length=30)),
                ('office_address', models.CharField(max_length=400)),
                ('contact_details', models.CharField(max_length=400)),
                ('is_active', models.BooleanField(default=False)),
            ],
            bases=('it_dashboard.itmetafield',),
        ),
        migrations.CreateModel(
            name='IT_Homepage_Segment',
            fields=[
                ('itmetafield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='it_dashboard.itmetafield')),
                ('photo_or_video', models.FileField(blank=True, null=True, upload_to='it/image/segment/')),
            ],
            bases=('it_dashboard.itmetafield',),
        ),
        migrations.CreateModel(
            name='IT_Notice_Board',
            fields=[
                ('itmetafield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='it_dashboard.itmetafield')),
                ('title', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Deactivate', 'Deactivate'), ('Expired', 'Expired')], default='Active', max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='it/file/notice-board/')),
                ('is_active', models.BooleanField(default=False)),
            ],
            bases=('it_dashboard.itmetafield',),
        ),
        migrations.CreateModel(
            name='IT_Office_Address',
            fields=[
                ('itmetafield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='it_dashboard.itmetafield')),
                ('address', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=140)),
                ('phone', models.CharField(max_length=14)),
                ('fax', models.CharField(max_length=20)),
            ],
            bases=('it_dashboard.itmetafield',),
        ),
        migrations.CreateModel(
            name='IT_Order_Card',
            fields=[
                ('itmetafield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='it_dashboard.itmetafield')),
                ('title', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='it/image/order-card/')),
                ('file', models.FileField(blank=True, null=True, upload_to='it/file/order-card/')),
                ('is_active', models.BooleanField(default=False)),
            ],
            bases=('it_dashboard.itmetafield',),
        ),
        migrations.CreateModel(
            name='IT_Our_Services',
            fields=[
                ('itmetafield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='it_dashboard.itmetafield')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='it/image/services-icons/')),
                ('title', models.CharField(max_length=500)),
                ('tags', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            bases=('it_dashboard.itmetafield',),
        ),
        migrations.CreateModel(
            name='IT_Payment_Logo',
            fields=[
                ('itmetafield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='it_dashboard.itmetafield')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='it/image/payment-logo/')),
            ],
            bases=('it_dashboard.itmetafield',),
        ),
        migrations.CreateModel(
            name='IT_Security_Page',
            fields=[
                ('itmetafield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='it_dashboard.itmetafield')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            bases=('it_dashboard.itmetafield',),
        ),
        migrations.CreateModel(
            name='IT_Social_Media',
            fields=[
                ('itmetafield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='it_dashboard.itmetafield')),
                ('name', models.CharField(max_length=150)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='it/image/social-media-icon/')),
                ('url', models.URLField(max_length=500)),
            ],
            bases=('it_dashboard.itmetafield',),
        ),
        migrations.CreateModel(
            name='IT_Subscriptions',
            fields=[
                ('itmetafield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='it_dashboard.itmetafield')),
                ('email', models.EmailField(max_length=150)),
            ],
            bases=('it_dashboard.itmetafield',),
        ),
        migrations.CreateModel(
            name='IT_Support_Company_Logo',
            fields=[
                ('itmetafield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='it_dashboard.itmetafield')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='it/image/comapny-logo/')),
            ],
            bases=('it_dashboard.itmetafield',),
        ),
        migrations.CreateModel(
            name='IT_Technology_Icon',
            fields=[
                ('itmetafield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='it_dashboard.itmetafield')),
                ('title', models.CharField(max_length=150)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='it/image/technology-icons/')),
            ],
            bases=('it_dashboard.itmetafield',),
        ),
        migrations.CreateModel(
            name='IT_ThreeCardSection',
            fields=[
                ('itmetafield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='it_dashboard.itmetafield')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='it/image/three-card-icons/')),
                ('title', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            bases=('it_dashboard.itmetafield',),
        ),
        migrations.CreateModel(
            name='IT_TimeData',
            fields=[
                ('itmetafield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='it_dashboard.itmetafield')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('day', models.PositiveSmallIntegerField()),
                ('hour', models.PositiveSmallIntegerField()),
                ('second', models.PositiveSmallIntegerField()),
            ],
            bases=('it_dashboard.itmetafield',),
        ),
        migrations.CreateModel(
            name='IT_TwoCardCustomerFeedback',
            fields=[
                ('itmetafield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='it_dashboard.itmetafield')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='it/image/two-card-customer-feedback/')),
                ('title', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            bases=('it_dashboard.itmetafield',),
        ),
        migrations.CreateModel(
            name='IT_WebsiteBanner',
            fields=[
                ('itmetafield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='it_dashboard.itmetafield')),
                ('header', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('image_and_video', models.FileField(blank=True, null=True, upload_to='it/image/banners/')),
            ],
            bases=('it_dashboard.itmetafield',),
        ),
        migrations.CreateModel(
            name='IT_WebsiteLogo',
            fields=[
                ('itmetafield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='it_dashboard.itmetafield')),
                ('image', models.ImageField(blank=True, null=True, upload_to='it/image/logo/')),
            ],
            bases=('it_dashboard.itmetafield',),
        ),
        migrations.CreateModel(
            name='IT_CallRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording', models.FileField(upload_to='static/call_recordings/')),
                ('duration', models.DurationField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('flag', models.CharField(blank=True, max_length=255, null=True)),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='it_call_recordings_made', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='it_call_recordings_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='IT_ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('flag', models.CharField(default='Flag', max_length=255)),
                ('admin_flag', models.CharField(default='Flag', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='it_received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='it_sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IT_Footer_Section_3',
            fields=[
                ('itmetafield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='it_dashboard.itmetafield')),
                ('title', models.CharField(max_length=50)),
                ('topics', models.ManyToManyField(to='it_dashboard.it_footer_section_topics')),
            ],
            bases=('it_dashboard.itmetafield',),
        ),
        migrations.CreateModel(
            name='IT_Footer_Section_2',
            fields=[
                ('itmetafield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='it_dashboard.itmetafield')),
                ('title', models.CharField(max_length=50)),
                ('topics', models.ManyToManyField(to='it_dashboard.it_footer_section_topics')),
            ],
            bases=('it_dashboard.itmetafield',),
        ),
        migrations.CreateModel(
            name='IT_Footer_Section_1',
            fields=[
                ('itmetafield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='it_dashboard.itmetafield')),
                ('title', models.CharField(max_length=50)),
                ('topics', models.ManyToManyField(to='it_dashboard.it_footer_section_topics')),
            ],
            bases=('it_dashboard.itmetafield',),
        ),
        migrations.CreateModel(
            name='IT_Technology',
            fields=[
                ('itmetafield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='it_dashboard.itmetafield')),
                ('name', models.CharField(max_length=150)),
                ('technoloies', models.ManyToManyField(to='it_dashboard.it_technology_icon')),
            ],
            bases=('it_dashboard.itmetafield',),
        ),
    ]
