# Generated by Django 5.0.2 on 2024-03-20 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('it_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='it_technology',
            old_name='technoloies',
            new_name='technologies',
        ),
    ]
