from django.contrib import admin
from .models import *

# Register your models here.
admin.site.register(Logo)
admin.site.register(Banner)
admin.site.register(TwoCardCustomerFeedback)
admin.site.register(ThreeCardSection)
admin.site.register(FourCardSection)
admin.site.register(CardTemplate)
admin.site.register(BlogCard)
admin.site.register(TimeData)
admin.site.register(HomepageSegment)
admin.site.register(SupportCompanyLogo)
admin.site.register(GlobalLocation)
admin.site.register(ContactUs)
admin.site.register(TechnologyIcon)
admin.site.register(Technology)
admin.site.register(Civil_Arcitecture_Images)
admin.site.register(Civil_Arcitecture)
admin.site.register(Civil_Feature_Work_Category)
admin.site.register(Civil_Feature_Work)
admin.site.register(OurServices)
admin.site.register(NoticeBoard)
admin.site.register(OrderCard)
admin.site.register(SecurityPage)
admin.site.register(CompanyMember)
admin.site.register(OfficeAddress)
admin.site.register(PaymentLogo)
admin.site.register(SocialMedia)
admin.site.register(Subscriptions)
admin.site.register(FooterSectionTopics)
admin.site.register(FooterSection1)
admin.site.register(FooterSection2)
admin.site.register(FooterSection3)
