# Generated by Django 5.0.2 on 2024-03-19 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Civil_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=300)),
                ('project_file', models.FileField(blank=True, null=True, upload_to='civil/order/project-file/')),
                ('related_file', models.FileField(blank=True, null=True, upload_to='civil/order/related-file/')),
                ('user_information_form', models.FileField(blank=True, null=True, upload_to='civil/order/user-information-form/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Payment', 'Payment'), ('Waiting', 'Waiting'), ('Working', 'Working'), ('Complited', 'Complited'), ('Cancel', 'Cancel')], default='Pending', max_length=40)),
                ('piority', models.CharField(choices=[('Normal', 'Normal'), ('Medium', 'Medium'), ('Emergency', 'Emergency')], default='Normal', max_length=40)),
                ('currency', models.CharField(blank=True, choices=[('USD', 'USD'), ('BDT', 'BDT'), ('INR', 'INR'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('CAD', 'CAD')], max_length=20, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_online_deposite', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_offline_deposite', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount_remain', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('profit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='civil_user_order', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_update_at', 'created_at', 'delivery_date'],
            },
        ),
        migrations.CreateModel(
            name='Civil_Order_Admin_Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_box', models.TextField()),
                ('file_or_image', models.FileField(blank=True, null=True, upload_to='civil/order/note-file/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='civil_order_note', to='civil.civil_order')),
            ],
        ),
        migrations.CreateModel(
            name='Civil_Order_Work_Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_box', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='civil_order_work_document', to='civil.civil_order')),
            ],
        ),
    ]
