# Generated by Django 5.0.2 on 2024-03-20 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Civil_Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='civil/image/bank_icons/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='civil/image/bank_qr_codes/')),
                ('account_details', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Civil_MobileWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='civil/image/mobile_wallet_icons/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='civil/image/mobile_wallet_qr_codes/')),
                ('account_details', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Civil_OfflineCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('payment_receipt_person_name', models.CharField(max_length=100)),
                ('payment_receipt_person_id', models.CharField(max_length=100)),
                ('check_holder_name', models.CharField(max_length=100)),
                ('check_holder_gmail', models.EmailField(max_length=254)),
                ('check_holder_phone_number', models.CharField(max_length=14)),
                ('check_number', models.CharField(max_length=100, unique=True)),
                ('check_security_code', models.CharField(max_length=100, unique=True)),
                ('currency_iso', models.CharField(max_length=3)),
                ('check_amount', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('check_number', 'check_security_code')},
            },
        ),
        migrations.CreateModel(
            name='Civil_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(blank=True, choices=[('USD', 'USD'), ('BDT', 'BDT')], max_length=3, null=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_type', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=10)),
                ('payment_method', models.CharField(blank=True, choices=[('Bank', 'Bank'), ('Mobile', 'Mobile')], max_length=10, null=True)),
                ('is_varified', models.BooleanField(default=False)),
                ('is_refund', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('paymend_added', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='civil_bank', to='civil.civil_bank')),
                ('mobile_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='civil_mobile_wallet', to='civil.civil_mobilewallet')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='civil_order_payment', to='civil.civil_order')),
            ],
        ),
        migrations.CreateModel(
            name='Civil_OfflinePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('receipt_person_name', models.CharField(max_length=100)),
                ('receipt_person_id', models.CharField(max_length=100)),
                ('check_holder_name', models.CharField(max_length=100)),
                ('check_holder_phone_number', models.CharField(max_length=14)),
                ('check_number', models.CharField(max_length=100)),
                ('check_security_code', models.CharField(max_length=100)),
                ('check_receipt', models.FileField(blank=True, null=True, upload_to='civil/image/check_receipt/')),
                ('is_varified', models.BooleanField(default=False)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offline_payment', to='civil.civil_payment')),
            ],
        ),
        migrations.CreateModel(
            name='Civil_MobilePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=100)),
                ('mobile_wallet_name', models.CharField(max_length=100)),
                ('account_type', models.CharField(max_length=100)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('transaction_receipt', models.ImageField(blank=True, null=True, upload_to='civil/image/transaction_receipts/')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_payment', to='civil.civil_payment')),
            ],
        ),
        migrations.CreateModel(
            name='Civil_BankPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('transaction_receipt', models.ImageField(blank=True, null=True, upload_to='civil/image/transaction_receipts/')),
                ('additional_info', models.TextField(blank=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_payment', to='civil.civil_payment')),
            ],
        ),
        migrations.CreateModel(
            name='Civil_Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_method', models.CharField(blank=True, choices=[('Bank', 'Bank'), ('Mobile', 'Mobile')], max_length=50, null=True)),
                ('currency', models.CharField(blank=True, editable=False, max_length=10, null=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Complete', 'Complete'), ('Cancel', 'Cancel')], default='Pending', max_length=50)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('preferred_contact_method', models.CharField(blank=True, max_length=20, null=True)),
                ('reason_for_refund', models.TextField()),
                ('proof_of_payment', models.FileField(blank=True, null=True, upload_to='civil/image/refund_proofs/')),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('feedback_or_suggestions', models.TextField(blank=True, null=True)),
                ('documentation_or_evidence', models.FileField(blank=True, null=True, upload_to='civil/image/refund_documents/')),
                ('specific_issue_details', models.TextField(blank=True, null=True)),
                ('additional_comments', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('paymend_added', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_refund', to='civil.civil_order')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_refund', to='civil.civil_payment')),
            ],
        ),
        migrations.CreateModel(
            name='Civil_Mobile_Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_mobile_wallet_name', models.CharField(max_length=100)),
                ('recipient_wallet_account_name', models.CharField(max_length=100)),
                ('recipient_wallet_account_number', models.CharField(max_length=100)),
                ('account_info', models.TextField()),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('refund', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='civil_mobile_refund', to='civil.civil_refund')),
            ],
        ),
        migrations.CreateModel(
            name='Civil_Bank_Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_bank_name', models.CharField(max_length=100)),
                ('recipient_bank_account_name', models.CharField(max_length=100)),
                ('recipient_bank_account_number', models.CharField(max_length=100)),
                ('recipient_bank_routing_name', models.CharField(max_length=100)),
                ('iban_or_swift_code', models.CharField(max_length=100)),
                ('account_info', models.TextField()),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('refund', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='civil_bank_refund', to='civil.civil_refund')),
            ],
        ),
    ]
