# Generated by Django 5.0.2 on 2024-03-27 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IT_Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='it/image/bank_icons/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='it/image/bank_qr_codes/')),
                ('account_details', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='IT_MobileWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='it/image/mobile_wallet_icons/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='it/image/mobile_wallet_qr_codes/')),
                ('account_details', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='IT_OfflineCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('payment_receipt_person_name', models.CharField(max_length=100)),
                ('payment_receipt_person_id', models.CharField(max_length=100)),
                ('check_holder_name', models.CharField(max_length=100)),
                ('check_holder_gmail', models.EmailField(max_length=254)),
                ('check_holder_phone_number', models.CharField(max_length=14)),
                ('check_number', models.CharField(max_length=100, unique=True)),
                ('check_security_code', models.CharField(max_length=100, unique=True)),
                ('currency_iso', models.CharField(max_length=3)),
                ('check_amount', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('check_number', 'check_security_code')},
            },
        ),
        migrations.CreateModel(
            name='IT_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=300)),
                ('project_file', models.FileField(blank=True, null=True, upload_to='it/order/project-file/')),
                ('related_file', models.FileField(blank=True, null=True, upload_to='it/order/related-file/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Payment', 'Payment'), ('Waiting', 'Waiting'), ('Working', 'Working'), ('Complited', 'Complited'), ('Cancel', 'Cancel')], default='Pending', max_length=40)),
                ('piority', models.CharField(choices=[('Normal', 'Normal'), ('Medium', 'Medium'), ('Emergency', 'Emergency')], default='Normal', max_length=40)),
                ('currency', models.CharField(blank=True, choices=[('USD', 'USD'), ('BDT', 'BDT'), ('INR', 'INR'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('CAD', 'CAD')], max_length=20, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_online_deposite', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_offline_deposite', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount_remain', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('profit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_only_me', models.BooleanField(default=False)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='it_order', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_update_at', 'created_at', 'delivery_date'],
            },
        ),
        migrations.CreateModel(
            name='IT_Order_Admin_Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_box', models.TextField()),
                ('file_or_image', models.FileField(blank=True, null=True, upload_to='it/order/note-file/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='it_order_note', to='it.it_order')),
            ],
        ),
        migrations.CreateModel(
            name='IT_Order_Work_Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_box', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='it_order_work_document', to='it.it_order')),
            ],
        ),
        migrations.CreateModel(
            name='IT_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(blank=True, choices=[('USD', 'USD'), ('BDT', 'BDT')], max_length=3, null=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_type', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=10)),
                ('payment_method', models.CharField(blank=True, choices=[('Bank', 'Bank'), ('Mobile', 'Mobile')], max_length=10, null=True)),
                ('is_varified', models.BooleanField(default=False)),
                ('is_refund', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('paymend_added', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='it_bank', to='it.it_bank')),
                ('mobile_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='it_mobile_wallet', to='it.it_mobilewallet')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='it_order_payment', to='it.it_order')),
            ],
        ),
        migrations.CreateModel(
            name='IT_OfflinePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('receipt_person_name', models.CharField(max_length=100)),
                ('receipt_person_id', models.CharField(max_length=100)),
                ('check_holder_name', models.CharField(max_length=100)),
                ('check_holder_phone_number', models.CharField(max_length=14)),
                ('check_number', models.CharField(max_length=100)),
                ('check_security_code', models.CharField(max_length=100)),
                ('check_receipt', models.FileField(blank=True, null=True, upload_to='it/image/check_receipt/')),
                ('is_varified', models.BooleanField(default=False)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offline_payment', to='it.it_payment')),
            ],
        ),
        migrations.CreateModel(
            name='IT_MobilePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=100)),
                ('mobile_wallet_name', models.CharField(max_length=100)),
                ('account_type', models.CharField(max_length=100)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('transaction_receipt', models.ImageField(blank=True, null=True, upload_to='it/image/transaction_receipts/')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_payment', to='it.it_payment')),
            ],
        ),
        migrations.CreateModel(
            name='IT_BankPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('transaction_receipt', models.ImageField(blank=True, null=True, upload_to='it/image/transaction_receipts/')),
                ('additional_info', models.TextField(blank=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_payment', to='it.it_payment')),
            ],
        ),
        migrations.CreateModel(
            name='IT_Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_method', models.CharField(blank=True, choices=[('Bank', 'Bank'), ('Mobile', 'Mobile')], max_length=50, null=True)),
                ('currency', models.CharField(blank=True, editable=False, max_length=10, null=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Complete', 'Complete'), ('Cancel', 'Cancel')], default='Pending', max_length=50)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('preferred_contact_method', models.CharField(blank=True, max_length=20, null=True)),
                ('reason_for_refund', models.TextField()),
                ('proof_of_payment', models.FileField(blank=True, null=True, upload_to='it/image/refund_proofs/')),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('feedback_or_suggestions', models.TextField(blank=True, null=True)),
                ('documentation_or_evidence', models.FileField(blank=True, null=True, upload_to='it/image/refund_documents/')),
                ('specific_issue_details', models.TextField(blank=True, null=True)),
                ('additional_comments', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('paymend_added', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='it_order_refund', to='it.it_order')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='it_payment_refund', to='it.it_payment')),
            ],
        ),
        migrations.CreateModel(
            name='IT_Mobile_Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_mobile_wallet_name', models.CharField(max_length=100)),
                ('recipient_wallet_account_name', models.CharField(max_length=100)),
                ('recipient_wallet_account_number', models.CharField(max_length=100)),
                ('account_info', models.TextField(blank=True, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('refund', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='it_mobile_refund', to='it.it_refund')),
            ],
        ),
        migrations.CreateModel(
            name='IT_Bank_Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_bank_name', models.CharField(max_length=100)),
                ('recipient_bank_account_name', models.CharField(max_length=100)),
                ('recipient_bank_account_number', models.CharField(max_length=100)),
                ('recipient_bank_routing_name', models.CharField(max_length=100)),
                ('iban_or_swift_code', models.CharField(max_length=100)),
                ('account_info', models.TextField(blank=True, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('refund', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='it_bank_refund', to='it.it_refund')),
            ],
        ),
    ]
