# Generated by Django 5.0.2 on 2024-03-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0002_it_bank_it_mobilewallet_it_offlinecheck_it_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='it_order',
            name='is_only_me',
            field=models.BooleanField(default=False),
        ),
    ]
