# Generated by Django 5.0.2 on 2024-03-28 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('IT', 'IT'), ('Civil', 'Civil')], max_length=10)),
                ('header', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('image_and_video', models.FileField(blank=True, null=True, upload_to='image/banners/')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlogCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('IT', 'IT'), ('Civil', 'Civil')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/blog-card/')),
                ('title', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('IT', 'IT'), ('Civil', 'Civil')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/template-card/')),
                ('title', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Civil_Arcitecture_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/arcitecture-image/')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Civil_Feature_Work_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Civil_Live_Chat_Admin_Sound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('IT', 'IT'), ('Civil', 'Civil')], max_length=10)),
                ('admin_live_chat_notification_sound', models.FileField(blank=True, null=True, upload_to='civil/sound/admin_live_chat_notification_sound/')),
                ('admin_live_call_ringtone', models.FileField(blank=True, null=True, upload_to='civil/sound/admin_live_call_ringtone/')),
                ('user_cannot_call_admin_sound', models.FileField(blank=True, null=True, upload_to='civil/sound/user_cannot_call_admin_sound/')),
            ],
        ),
        migrations.CreateModel(
            name='Civil_User_Order_Sound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('IT', 'IT'), ('Civil', 'Civil')], max_length=10)),
                ('order_chat_notification_tone', models.FileField(blank=True, null=True, upload_to='civil/sound/order_chat_notification_tone/')),
                ('order_call_ringtone', models.FileField(blank=True, null=True, upload_to='civil/sound/order_call_ringtone/')),
            ],
        ),
        migrations.CreateModel(
            name='Civil_User_Sound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('IT', 'IT'), ('Civil', 'Civil')], max_length=10)),
                ('website_entry_sound', models.FileField(blank=True, null=True, upload_to='civil/sound/entry_sound/')),
                ('live_chat_talk_sound', models.FileField(blank=True, null=True, upload_to='civil/sound/live_chat_talk_sound/')),
                ('live_chat_turned_off_sound', models.FileField(blank=True, null=True, upload_to='civil/sound/live_chat_turned_off_sound/')),
                ('user_live_chat_notification_sound', models.FileField(blank=True, null=True, upload_to='civil/sound/user_live_chat_notification_sound/')),
                ('user_live_call_ringtone', models.FileField(blank=True, null=True, upload_to='civil/sound/user_live_call_ringtone/')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('IT', 'IT'), ('Civil', 'Civil')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/company-member/')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=150)),
                ('phone_number', models.CharField(max_length=14)),
                ('address', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('IT', 'IT'), ('Civil', 'Civil')], max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=150)),
                ('phone_number', models.CharField(max_length=15)),
                ('subject', models.CharField(max_length=600)),
                ('message', models.TextField()),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FooterSectionTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('IT', 'IT'), ('Civil', 'Civil')], max_length=10)),
                ('title', models.CharField(max_length=50)),
                ('topic_url', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FourCardSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('IT', 'IT'), ('Civil', 'Civil')], max_length=10)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='image/four-card-icons/')),
                ('title', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GlobalLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('IT', 'IT'), ('Civil', 'Civil')], max_length=10)),
                ('flag_logo', models.ImageField(blank=True, null=True, upload_to='image/global-location-flag/')),
                ('country_name', models.CharField(max_length=30)),
                ('office_address', models.CharField(max_length=400)),
                ('contact_details', models.CharField(max_length=400)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomepageSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('IT', 'IT'), ('Civil', 'Civil')], max_length=10)),
                ('photo_or_video', models.FileField(blank=True, null=True, upload_to='image/segment/')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('IT', 'IT'), ('Civil', 'Civil')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/logo/')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NoticeBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('IT', 'IT'), ('Civil', 'Civil')], max_length=10)),
                ('title', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Deactivate', 'Deactivate'), ('Expired', 'Expired')], default='Active', max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='file/notice-board/')),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfficeAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('IT', 'IT'), ('Civil', 'Civil')], max_length=10)),
                ('address', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=140)),
                ('phone', models.CharField(max_length=14)),
                ('fax', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('IT', 'IT'), ('Civil', 'Civil')], max_length=10)),
                ('title', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/order-card/')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OurServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('IT', 'IT'), ('Civil', 'Civil')], max_length=10)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='image/services-icons/')),
                ('title', models.CharField(max_length=500)),
                ('tags', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('IT', 'IT'), ('Civil', 'Civil')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='image/payment-logo/')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecurityPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('IT', 'IT'), ('Civil', 'Civil')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('IT', 'IT'), ('Civil', 'Civil')], max_length=10)),
                ('name', models.CharField(max_length=150)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='image/social-media-icon/')),
                ('url', models.URLField(max_length=500)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('IT', 'IT'), ('Civil', 'Civil')], max_length=10)),
                ('email', models.EmailField(max_length=150)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupportCompanyLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('IT', 'IT'), ('Civil', 'Civil')], max_length=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='image/company-logo/')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TechnologyIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='image/technology-icons/')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ThreeCardSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('IT', 'IT'), ('Civil', 'Civil')], max_length=10)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='image/three-card-icons/')),
                ('title', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('day', models.PositiveSmallIntegerField()),
                ('hour', models.PositiveSmallIntegerField()),
                ('second', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TwoCardCustomerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('IT', 'IT'), ('Civil', 'Civil')], max_length=10)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='image/two-card-customer-feedback/')),
                ('title', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Civil_Arcitecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('plan_details', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('describtion', models.TextField()),
                ('feature_image', models.ManyToManyField(to='home_page.civil_arcitecture_images')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Civil_Feature_Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/feature-work-image/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_work_category', to='home_page.civil_feature_work_category')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FooterSection3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('IT', 'IT'), ('Civil', 'Civil')], max_length=10)),
                ('title', models.CharField(max_length=50)),
                ('topics', models.ManyToManyField(to='home_page.footersectiontopics')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FooterSection2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('IT', 'IT'), ('Civil', 'Civil')], max_length=10)),
                ('title', models.CharField(max_length=50)),
                ('topics', models.ManyToManyField(to='home_page.footersectiontopics')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FooterSection1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('IT', 'IT'), ('Civil', 'Civil')], max_length=10)),
                ('title', models.CharField(max_length=50)),
                ('topics', models.ManyToManyField(to='home_page.footersectiontopics')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderApplicationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('IT', 'IT'), ('Civil', 'Civil')], max_length=10)),
                ('full_name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='')),
                ('fathers_name', models.CharField(max_length=50)),
                ('mothers_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=10)),
                ('religion', models.CharField(max_length=50)),
                ('speaking_language', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=50)),
                ('month_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nationality', models.CharField(max_length=50)),
                ('national_id_or_passport_number', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state_or_province', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=10)),
                ('address', models.TextField(blank=True, null=True)),
                ('cell_phone_number', models.CharField(max_length=20)),
                ('fax_number', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('project_type', models.CharField(choices=[('Personal', 'Personal'), ('Company', 'Company'), ('Government', 'Government')], max_length=10)),
                ('technology_used', models.CharField(max_length=100)),
                ('colors_used', models.CharField(max_length=100)),
                ('project_deadline', models.DateField()),
                ('project_description', models.TextField(blank=True, null=True)),
                ('additional_information', models.TextField(blank=True, null=True)),
                ('company_name', models.CharField(max_length=50)),
                ('company_type', models.CharField(max_length=50)),
                ('company_phone_number', models.CharField(max_length=20)),
                ('company_email_address', models.EmailField(max_length=254)),
                ('company_location_address', models.TextField()),
                ('company_website_url', models.URLField()),
                ('project_manager_signature', models.CharField(max_length=255)),
                ('applicant_signature', models.CharField(max_length=255)),
                ('agree', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_order_application_form', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('technology_icons', models.ManyToManyField(to='home_page.technologyicon')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
    ]
